let Emojis = {
  directions: {
    down: "⬆",
    up: "⬇",
    left: "⬅",
    right: "➡",
    "up-left": "↖",
    "up-right": "↗",
    "down-left": "↙",
    "down-right": "↘",
    "up-down": "↕",
    "left-right": "↔",
  },
  "hand-directions": {
    left: "👈",
    right: "👉",
    up: "👆",
    down: "👇",
  },
  tasks: {
    progress: "💪",
    completed: "✅",
    incomplete: "❌",
    pending: "⏳",
  },
  misc: {
    check: "✅",
    cross: "❌",
    info: "ℹ",
    warning: "⚠",
    question: "❓",
    exclamation: "❗",
    plus: "➕",
    minus: "➖",
  },
  weather: {
    "clear-day": "🌞",
    "clear-night": "🌚",
    rain: "🌧",
    snow: "🌨",
    sleet: "🌨",
    wind: "🌬",
    fog: "🌫",
    cloudy: "☁️",
    "partly-cloudy-day": "🌤",
    "partly-cloudy-night": "🌙",
  },
  emotions: {
    happy: "😀",
    sad: "😢",
    angry: "😠",
    excited: "😀",
    bored: "😐",
    confused: "😕",
    sleepy: "😴",
    surprised: "😮",
    scared: "😨",
    disappointed: "😞",
    embarrassed: "😳",
    tired: "😩",
    lonely: "😓",
    confident: "😇",
    shy: "😯",
    embarrassed: "😳",
    tired: "😩",
    lonely: "😓",
    confident: "😇",
    shy: "😯",
    embarrassed: "😳",
    tired: "😩",
    lonely: "😓",
    confident: "😇",
    shy: "😯",
    embarrassed: "😳",
  },
};

// Emojis = {
// done : ✅,
// some : 👈,
// some : 👆,
// some : ☝️,
// some : 👇,
// some : 👍,
// some : 🤏,
// some : 👀,
// some : 👎,
// some : ⤴️,
// some : 🤛,
// some : ⬇️,
// some : ✊r,
// some : 🆗,
// some : ↪️,
// some : ↩️,
// some : 🖕,
// some : 👋,
// some : ↖️,
// some : 🤚,
// some : ⤵️,
// some : 👈,
// some : 👆,
// some : ☝️,
// some : 👇,
// some : 👍,
// some : 🤏,
// some : 👀,
// some : 👎,
// some : ⤴️,
// some : 🤛,
// some : ⬇️,
// some : ✊r,
// some : 🆗,
// some : ↪️,
// some : ↩️,
// some : 🖕,
// some : 👋,
// some : ↖️,
// some : 🤚,
// some : ⤵️,
// }
